# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FormatImg": "data.ipynb",
         "get_out_channels": "pytorch_tensorrt_conversion.ipynb",
         "conv_layer": "tensorflow_tensorrt_conversion.ipynb",
         "up_conv_layer": "tensorflow_tensorrt_conversion.ipynb",
         "get_encoder": "tensorflow_tensorrt_conversion.ipynb",
         "UNET_TRT": "tensorflow_tensorrt_conversion.ipynb",
         "tensorrt_inference": "tensorrt_inference_py.ipynb",
         "format": "data.ipynb",
         "preprocess_tfrecord": "data.ipynb",
         "preprocess_file": "data.ipynb",
         "preprocess_raw": "data.ipynb"}

modules = ["data.py",
           "tensorrt_py.py",
           "tensorrt_inference_py.py",
           "tensorrt_conversion_py.py",
           "pytorch_tensorrt_conversion.py",
           "tensorflow_tensorrt_conversion.py"]

doc_url = "https://justinblaber.github.io/test_fast_inference/"

git_url = "https://github.com/justinblaber/test_fast_inference/tree/master/"

def custom_doc_links(name): return None
